# Generated by Django 4.2.5 on 2023-10-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_promoter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='image',
        ),
    ]
