# Generated by Django 4.2.5 on 2023-10-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_promoter_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='promoter',
        ),
    ]
