# Generated by Django 4.2.5 on 2023-10-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_promoter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('faq_type', models.CharField(choices=[('rent_trackung', 'Rent Tracking'), ('new_deposite', 'New_Deposite'), ('existing_deposite', 'Existing Deposit')], max_length=128)),
            ],
        ),
    ]
