# Generated by Django 4.2.5 on 2023-10-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='faq_type',
            field=models.CharField(choices=[('rent_tracking', 'Rent Tracking'), ('new_deposite', 'New Deposite'), ('existing_deposite', 'Existing Deposit')], max_length=128),
        ),
    ]
