# Generated by Django 4.2.5 on 2023-10-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_faq_faq_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='abcd', upload_to='testimonials/'),
            preserve_default=False,
        ),
    ]
